### ISSUE TITLE
error ascii codec

### ISSUE THREAD

**Issue by chtiprog** [marcwebbie/pysswords#10]
1) I added a new credential with an unicode character

    ➜  ~  pysswords -a
    Name: #######
    Login: ########  
    Password: 
    Type again: 
    Comment: site français

2) Pysswords throwns an error when listing credentials

    ➜  ~  pysswords   
    ERROR:root:'ascii' codec can't encode characters in position 816-817: ordinal not in range(128)

**Comment by marcwebbie** [comment]
Hello,

Pysswords doesn't handle unicode input from python2.

For now to fix your credential you can open the Pysswords for your credential and edit the comment manually this time using no unicode character.

for example, for a credential with Name: "example.com" and a login: "john"  and a Pyssword database at the default path: "~/.pysswords" you can do:

```
{EDITOR} ~/.pysswords/example.com/john.pyssword
```

Thanks for opening this issue.
