### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by kenetik** [marcwebbie/pysswords#13]
Didn't know any other way to contact you. https://marcwebbie.io/pysswords is down, let me know if you'd like for me to host a stable presence for this great project.

**Comment by marcwebbie** [comment]
Hello @kenetik 

Yes, I've seen the site was down, however it is now back live at:

+ http://pysswords.marcwebbie.io/
+ http://marcwebbie.io/pysswords/
+ http://marcwebbie.github.io/pysswords/

Thanks for opening the issue. ;)

PS: I will be closing for now, tell me more what you have in mind at marcwebbie@gmail.com
