### ISSUE TITLE
Tag releases new here as well

### ISSUE THREAD

**Issue by hnk** [marcwebbie/pysswords#22]
A little nitpicky, but I was confused as the latest release tagged here is 0.0.9 and on PyPi it is 0.0.12...

Thanks!

**Comment by marcwebbie** [comment]
Hello, 

You are right, I've been mostly depending on pip for the version management. 
Here is the link for latest version. https://github.com/marcwebbie/pysswords/releases/tag/v0.0.12

Thanks for the issue
