### ISSUE TITLE
Error during 'pysswords --init'

### ISSUE THREAD

**Issue by hnk** [marcwebbie/pysswords#23]
During my initial 'pysswords --init' run I run into the fillowing exception:
```python
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/gnupg/_meta.py", line 605, in _read_response
    result._handle_status(keyword, value)
  File "/usr/lib/python2.7/site-packages/gnupg/_parsers.py", line 862, in _handle_status
    raise ValueError("Unknown status message: %r" % key)
ValueError: Unknown status message: u'PINENTRY_LAUNCHED'

Database initialized in '/home/my-username/.pysswords'
```
If I ignore the error and try to add an entry using 'pysswords -a', I receive the following error:
```python
Database initialized in '/home/my-username/.pysswords'
```

I'm on Manjaro Linux (Arch derivate). Installed using pip, but systemwide using sudo.

**Comment by marcwebbie** [comment]
It seems to be a GPG issue system wide on Arch systems.

I've found those links here, maybe they can help you out: 

* https://github.com/OpenBazaar/OpenBazaar/issues/1143
* https://github.com/OpenBazaar/OpenBazaar/issues/1086

Thanks

**Comment by hnk** [comment]
Thanks for looking into this and sorry for my own lazyness. I should have done that myself. Especially now that I see in the error log, that the error happens within gnupg and not your package. I apologize.

I'll see what may need to be done about it and post about it here, so you can decide if you want to include this in documentation.

**Comment by marcwebbie** [comment]
No worries, any feedback is welcome even more in this early stage of development. :) 
And yes, please comment on the issue if you manage to find a solution.

Also, it might be useful for you, taking a a look at Pysswords on AUR: https://aur.archlinux.org/packages/python2-pysswords/

I will be closing the issue for now.
