### ISSUE TITLE
Sync passwords or password db between computers

### ISSUE THREAD

**Issue by SkiftCreative** [marcwebbie/pysswords#8]
I under stand that this could be a larger issue,  but I think a way to keep multiple computers in sync would be amazing.  This with browser support could make me want to use it over last pass.

So I see maybe 2 possibilities for syncing. 

1. Sync server. Similar to other pass managers. The db syncs with the online server making it available anywhere.

2. Allowing to easily export the db. Although more clunky to then sync the files manually

Now that I think about it,  would it be plausible to sync it over Google Drive or similar?

**Comment by marcwebbie** [comment]
Hello @SkiftCreative 

You can always sync your pysswords db directory through Google Drive, Dropbox, etc. That is one way to sync it.

I am working on an exporting feature that would freeze the Database so you could import it. I like the manual approach better. Sync server approach... think about Google Drive and Dropbox.

Thanks

**Comment by marcwebbie** [comment]
Exporting feature was added as of [version 0.0.9](https://github.com/marcwebbie/pysswords/releases/tag/v0.0.9)

Thanks
