### ISSUE TITLE
Initialize database after installing GPG gives "database exists" error

### ISSUE THREAD

**Issue by chtiprog** [marcwebbie/pysswords#9]
1) I did : ➜  ~  `pip install pysswords`
2) I try : ➜  ~  `pysswords --init`
I get this error : 
RuntimeError: GnuPG is not installed!
3) I installed GPG for MAC OS X from https://www.gnupg.org/download/
4) Finally I tried again :
```
➜  ~  pysswords --init
Passphrase for database: 
Type again: 
ERROR:root:Database exists
```

**Comment by marcwebbie** [comment]
Hello,

Since you tried to initialize the database in the default path, you can remove the corrupted database with:
```
rm -rf ~/.pysswords
```

Then you can try again:

```
pysswords --init
```

Thanks.
